source 'https://rubygems.org'
gem 'mongo_mapper'
gem "resque"
gem 'resque-web', require: 'resque_web'
gem 'bitly', '0.9.0'
gem 'tux'
gem 'rake'
gem 'bson_ext'
gem 'rest-client'
gem 'json'
gem 'hashie'