source 'https://rubygems.org'
gem 'mongo_mapper'
gem "resque", :git => 'git://github.com/resque/resque.git'
gem 'bitly', '0.9.0'
gem 'tux'
gem 'rake'
gem 'bson_ext'
gem 'rest-client'
gem 'json'
gem 'hashie'